// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: io/github/pixelmonaskarion/protomms/proto/proto_mms.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package io.github.pixelmonaskarion.protomms.proto;

@kotlin.jvm.JvmName("-initializeattachment")
public inline fun attachment(block: io.github.pixelmonaskarion.protomms.proto.AttachmentKt.Dsl.() -> kotlin.Unit): io.github.pixelmonaskarion.protomms.proto.ProtoMms.Attachment =
  io.github.pixelmonaskarion.protomms.proto.AttachmentKt.Dsl._create(io.github.pixelmonaskarion.protomms.proto.ProtoMms.Attachment.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `io.github.pixelmonaskarion.protomms.proto.Attachment`
 */
public object AttachmentKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: io.github.pixelmonaskarion.protomms.proto.ProtoMms.Attachment.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: io.github.pixelmonaskarion.protomms.proto.ProtoMms.Attachment.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): io.github.pixelmonaskarion.protomms.proto.ProtoMms.Attachment = _builder.build()

    /**
     * `string data = 1;`
     */
    public var data: kotlin.String
      @JvmName("getData")
      get() = _builder.getData()
      @JvmName("setData")
      set(value) {
        _builder.setData(value)
      }
    /**
     * `string data = 1;`
     */
    public fun clearData() {
      _builder.clearData()
    }

    /**
     * `string mime_type = 2;`
     */
    public var mimeType: kotlin.String
      @JvmName("getMimeType")
      get() = _builder.getMimeType()
      @JvmName("setMimeType")
      set(value) {
        _builder.setMimeType(value)
      }
    /**
     * `string mime_type = 2;`
     */
    public fun clearMimeType() {
      _builder.clearMimeType()
    }

    /**
     * `string file_name = 3;`
     */
    public var fileName: kotlin.String
      @JvmName("getFileName")
      get() = _builder.getFileName()
      @JvmName("setFileName")
      set(value) {
        _builder.setFileName(value)
      }
    /**
     * `string file_name = 3;`
     */
    public fun clearFileName() {
      _builder.clearFileName()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun io.github.pixelmonaskarion.protomms.proto.ProtoMms.Attachment.copy(block: io.github.pixelmonaskarion.protomms.proto.AttachmentKt.Dsl.() -> kotlin.Unit): io.github.pixelmonaskarion.protomms.proto.ProtoMms.Attachment =
  io.github.pixelmonaskarion.protomms.proto.AttachmentKt.Dsl._create(this.toBuilder()).apply { block() }._build()

