// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: io/github/pixelmonaskarion/protomms/proto/proto_mms.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package io.github.pixelmonaskarion.protomms.proto;

@kotlin.jvm.JvmName("-initializemessage")
public inline fun message(block: io.github.pixelmonaskarion.protomms.proto.MessageKt.Dsl.() -> kotlin.Unit): io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message =
  io.github.pixelmonaskarion.protomms.proto.MessageKt.Dsl._create(io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `io.github.pixelmonaskarion.protomms.proto.Message`
 */
public object MessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message = _builder.build()

    /**
     * `optional string text = 1;`
     */
    public var text: kotlin.String
      @JvmName("getText")
      get() = _builder.getText()
      @JvmName("setText")
      set(value) {
        _builder.setText(value)
      }
    /**
     * `optional string text = 1;`
     */
    public fun clearText() {
      _builder.clearText()
    }
    /**
     * `optional string text = 1;`
     * @return Whether the text field is set.
     */
    public fun hasText(): kotlin.Boolean {
      return _builder.hasText()
    }

    /**
     * `optional string attachments = 2;`
     */
    public var attachments: kotlin.String
      @JvmName("getAttachments")
      get() = _builder.getAttachments()
      @JvmName("setAttachments")
      set(value) {
        _builder.setAttachments(value)
      }
    /**
     * `optional string attachments = 2;`
     */
    public fun clearAttachments() {
      _builder.clearAttachments()
    }
    /**
     * `optional string attachments = 2;`
     * @return Whether the attachments field is set.
     */
    public fun hasAttachments(): kotlin.Boolean {
      return _builder.hasAttachments()
    }

    /**
     * `int32 message_id = 3;`
     */
    public var messageId: kotlin.Int
      @JvmName("getMessageId")
      get() = _builder.getMessageId()
      @JvmName("setMessageId")
      set(value) {
        _builder.setMessageId(value)
      }
    /**
     * `int32 message_id = 3;`
     */
    public fun clearMessageId() {
      _builder.clearMessageId()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class RecipientsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .io.github.pixelmonaskarion.protomms.proto.Recipient recipients = 4;`
     */
     public val recipients: com.google.protobuf.kotlin.DslList<io.github.pixelmonaskarion.protomms.proto.ProtoMms.Recipient, RecipientsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getRecipientsList()
      )
    /**
     * `repeated .io.github.pixelmonaskarion.protomms.proto.Recipient recipients = 4;`
     * @param value The recipients to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addRecipients")
    public fun com.google.protobuf.kotlin.DslList<io.github.pixelmonaskarion.protomms.proto.ProtoMms.Recipient, RecipientsProxy>.add(value: io.github.pixelmonaskarion.protomms.proto.ProtoMms.Recipient) {
      _builder.addRecipients(value)
    }
    /**
     * `repeated .io.github.pixelmonaskarion.protomms.proto.Recipient recipients = 4;`
     * @param value The recipients to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignRecipients")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<io.github.pixelmonaskarion.protomms.proto.ProtoMms.Recipient, RecipientsProxy>.plusAssign(value: io.github.pixelmonaskarion.protomms.proto.ProtoMms.Recipient) {
      add(value)
    }
    /**
     * `repeated .io.github.pixelmonaskarion.protomms.proto.Recipient recipients = 4;`
     * @param values The recipients to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllRecipients")
    public fun com.google.protobuf.kotlin.DslList<io.github.pixelmonaskarion.protomms.proto.ProtoMms.Recipient, RecipientsProxy>.addAll(values: kotlin.collections.Iterable<io.github.pixelmonaskarion.protomms.proto.ProtoMms.Recipient>) {
      _builder.addAllRecipients(values)
    }
    /**
     * `repeated .io.github.pixelmonaskarion.protomms.proto.Recipient recipients = 4;`
     * @param values The recipients to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllRecipients")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<io.github.pixelmonaskarion.protomms.proto.ProtoMms.Recipient, RecipientsProxy>.plusAssign(values: kotlin.collections.Iterable<io.github.pixelmonaskarion.protomms.proto.ProtoMms.Recipient>) {
      addAll(values)
    }
    /**
     * `repeated .io.github.pixelmonaskarion.protomms.proto.Recipient recipients = 4;`
     * @param index The index to set the value at.
     * @param value The recipients to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setRecipients")
    public operator fun com.google.protobuf.kotlin.DslList<io.github.pixelmonaskarion.protomms.proto.ProtoMms.Recipient, RecipientsProxy>.set(index: kotlin.Int, value: io.github.pixelmonaskarion.protomms.proto.ProtoMms.Recipient) {
      _builder.setRecipients(index, value)
    }
    /**
     * `repeated .io.github.pixelmonaskarion.protomms.proto.Recipient recipients = 4;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearRecipients")
    public fun com.google.protobuf.kotlin.DslList<io.github.pixelmonaskarion.protomms.proto.ProtoMms.Recipient, RecipientsProxy>.clear() {
      _builder.clearRecipients()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message.copy(block: io.github.pixelmonaskarion.protomms.proto.MessageKt.Dsl.() -> kotlin.Unit): io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message =
  io.github.pixelmonaskarion.protomms.proto.MessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

