// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: io/github/pixelmonaskarion/protomms/proto/proto_mms.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package io.github.pixelmonaskarion.protomms.proto;

