// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io/github/pixelmonaskarion/protomms/proto/proto_mms.proto

package io.github.pixelmonaskarion.protomms.proto;

public final class ProtoMms {
  private ProtoMms() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.github.pixelmonaskarion.protomms.proto.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string text = 1;</code>
     * @return Whether the text field is set.
     */
    boolean hasText();
    /**
     * <code>optional string text = 1;</code>
     * @return The text.
     */
    java.lang.String getText();
    /**
     * <code>optional string text = 1;</code>
     * @return The bytes for text.
     */
    com.google.protobuf.ByteString
        getTextBytes();

    /**
     * <code>optional string attachments = 2;</code>
     * @return Whether the attachments field is set.
     */
    boolean hasAttachments();
    /**
     * <code>optional string attachments = 2;</code>
     * @return The attachments.
     */
    java.lang.String getAttachments();
    /**
     * <code>optional string attachments = 2;</code>
     * @return The bytes for attachments.
     */
    com.google.protobuf.ByteString
        getAttachmentsBytes();

    /**
     * <code>string message_id = 3;</code>
     * @return The messageId.
     */
    java.lang.String getMessageId();
    /**
     * <code>string message_id = 3;</code>
     * @return The bytes for messageId.
     */
    com.google.protobuf.ByteString
        getMessageIdBytes();

    /**
     * <code>.io.github.pixelmonaskarion.protomms.proto.Address sender = 4;</code>
     * @return Whether the sender field is set.
     */
    boolean hasSender();
    /**
     * <code>.io.github.pixelmonaskarion.protomms.proto.Address sender = 4;</code>
     * @return The sender.
     */
    io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address getSender();
    /**
     * <code>.io.github.pixelmonaskarion.protomms.proto.Address sender = 4;</code>
     */
    io.github.pixelmonaskarion.protomms.proto.ProtoMms.AddressOrBuilder getSenderOrBuilder();

    /**
     * <code>repeated .io.github.pixelmonaskarion.protomms.proto.Address recipients = 5;</code>
     */
    java.util.List<io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address> 
        getRecipientsList();
    /**
     * <code>repeated .io.github.pixelmonaskarion.protomms.proto.Address recipients = 5;</code>
     */
    io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address getRecipients(int index);
    /**
     * <code>repeated .io.github.pixelmonaskarion.protomms.proto.Address recipients = 5;</code>
     */
    int getRecipientsCount();
    /**
     * <code>repeated .io.github.pixelmonaskarion.protomms.proto.Address recipients = 5;</code>
     */
    java.util.List<? extends io.github.pixelmonaskarion.protomms.proto.ProtoMms.AddressOrBuilder> 
        getRecipientsOrBuilderList();
    /**
     * <code>repeated .io.github.pixelmonaskarion.protomms.proto.Address recipients = 5;</code>
     */
    io.github.pixelmonaskarion.protomms.proto.ProtoMms.AddressOrBuilder getRecipientsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code io.github.pixelmonaskarion.protomms.proto.Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.github.pixelmonaskarion.protomms.proto.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      text_ = "";
      attachments_ = "";
      messageId_ = "";
      recipients_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.pixelmonaskarion.protomms.proto.ProtoMms.internal_static_io_github_pixelmonaskarion_protomms_proto_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.pixelmonaskarion.protomms.proto.ProtoMms.internal_static_io_github_pixelmonaskarion_protomms_proto_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message.class, io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message.Builder.class);
    }

    private int bitField0_;
    public static final int TEXT_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object text_ = "";
    /**
     * <code>optional string text = 1;</code>
     * @return Whether the text field is set.
     */
    @java.lang.Override
    public boolean hasText() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string text = 1;</code>
     * @return The text.
     */
    @java.lang.Override
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      }
    }
    /**
     * <code>optional string text = 1;</code>
     * @return The bytes for text.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ATTACHMENTS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object attachments_ = "";
    /**
     * <code>optional string attachments = 2;</code>
     * @return Whether the attachments field is set.
     */
    @java.lang.Override
    public boolean hasAttachments() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string attachments = 2;</code>
     * @return The attachments.
     */
    @java.lang.Override
    public java.lang.String getAttachments() {
      java.lang.Object ref = attachments_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        attachments_ = s;
        return s;
      }
    }
    /**
     * <code>optional string attachments = 2;</code>
     * @return The bytes for attachments.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAttachmentsBytes() {
      java.lang.Object ref = attachments_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        attachments_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGE_ID_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object messageId_ = "";
    /**
     * <code>string message_id = 3;</code>
     * @return The messageId.
     */
    @java.lang.Override
    public java.lang.String getMessageId() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageId_ = s;
        return s;
      }
    }
    /**
     * <code>string message_id = 3;</code>
     * @return The bytes for messageId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDER_FIELD_NUMBER = 4;
    private io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address sender_;
    /**
     * <code>.io.github.pixelmonaskarion.protomms.proto.Address sender = 4;</code>
     * @return Whether the sender field is set.
     */
    @java.lang.Override
    public boolean hasSender() {
      return sender_ != null;
    }
    /**
     * <code>.io.github.pixelmonaskarion.protomms.proto.Address sender = 4;</code>
     * @return The sender.
     */
    @java.lang.Override
    public io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address getSender() {
      return sender_ == null ? io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address.getDefaultInstance() : sender_;
    }
    /**
     * <code>.io.github.pixelmonaskarion.protomms.proto.Address sender = 4;</code>
     */
    @java.lang.Override
    public io.github.pixelmonaskarion.protomms.proto.ProtoMms.AddressOrBuilder getSenderOrBuilder() {
      return sender_ == null ? io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address.getDefaultInstance() : sender_;
    }

    public static final int RECIPIENTS_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private java.util.List<io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address> recipients_;
    /**
     * <code>repeated .io.github.pixelmonaskarion.protomms.proto.Address recipients = 5;</code>
     */
    @java.lang.Override
    public java.util.List<io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address> getRecipientsList() {
      return recipients_;
    }
    /**
     * <code>repeated .io.github.pixelmonaskarion.protomms.proto.Address recipients = 5;</code>
     */
    @java.lang.Override
    public java.util.List<? extends io.github.pixelmonaskarion.protomms.proto.ProtoMms.AddressOrBuilder> 
        getRecipientsOrBuilderList() {
      return recipients_;
    }
    /**
     * <code>repeated .io.github.pixelmonaskarion.protomms.proto.Address recipients = 5;</code>
     */
    @java.lang.Override
    public int getRecipientsCount() {
      return recipients_.size();
    }
    /**
     * <code>repeated .io.github.pixelmonaskarion.protomms.proto.Address recipients = 5;</code>
     */
    @java.lang.Override
    public io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address getRecipients(int index) {
      return recipients_.get(index);
    }
    /**
     * <code>repeated .io.github.pixelmonaskarion.protomms.proto.Address recipients = 5;</code>
     */
    @java.lang.Override
    public io.github.pixelmonaskarion.protomms.proto.ProtoMms.AddressOrBuilder getRecipientsOrBuilder(
        int index) {
      return recipients_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, text_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, attachments_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(messageId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, messageId_);
      }
      if (sender_ != null) {
        output.writeMessage(4, getSender());
      }
      for (int i = 0; i < recipients_.size(); i++) {
        output.writeMessage(5, recipients_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, text_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, attachments_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(messageId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, messageId_);
      }
      if (sender_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getSender());
      }
      for (int i = 0; i < recipients_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, recipients_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message)) {
        return super.equals(obj);
      }
      io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message other = (io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message) obj;

      if (hasText() != other.hasText()) return false;
      if (hasText()) {
        if (!getText()
            .equals(other.getText())) return false;
      }
      if (hasAttachments() != other.hasAttachments()) return false;
      if (hasAttachments()) {
        if (!getAttachments()
            .equals(other.getAttachments())) return false;
      }
      if (!getMessageId()
          .equals(other.getMessageId())) return false;
      if (hasSender() != other.hasSender()) return false;
      if (hasSender()) {
        if (!getSender()
            .equals(other.getSender())) return false;
      }
      if (!getRecipientsList()
          .equals(other.getRecipientsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasText()) {
        hash = (37 * hash) + TEXT_FIELD_NUMBER;
        hash = (53 * hash) + getText().hashCode();
      }
      if (hasAttachments()) {
        hash = (37 * hash) + ATTACHMENTS_FIELD_NUMBER;
        hash = (53 * hash) + getAttachments().hashCode();
      }
      hash = (37 * hash) + MESSAGE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getMessageId().hashCode();
      if (hasSender()) {
        hash = (37 * hash) + SENDER_FIELD_NUMBER;
        hash = (53 * hash) + getSender().hashCode();
      }
      if (getRecipientsCount() > 0) {
        hash = (37 * hash) + RECIPIENTS_FIELD_NUMBER;
        hash = (53 * hash) + getRecipientsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.github.pixelmonaskarion.protomms.proto.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.github.pixelmonaskarion.protomms.proto.Message)
        io.github.pixelmonaskarion.protomms.proto.ProtoMms.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.pixelmonaskarion.protomms.proto.ProtoMms.internal_static_io_github_pixelmonaskarion_protomms_proto_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.pixelmonaskarion.protomms.proto.ProtoMms.internal_static_io_github_pixelmonaskarion_protomms_proto_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message.class, io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message.Builder.class);
      }

      // Construct using io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        text_ = "";
        attachments_ = "";
        messageId_ = "";
        sender_ = null;
        if (senderBuilder_ != null) {
          senderBuilder_.dispose();
          senderBuilder_ = null;
        }
        if (recipientsBuilder_ == null) {
          recipients_ = java.util.Collections.emptyList();
        } else {
          recipients_ = null;
          recipientsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.pixelmonaskarion.protomms.proto.ProtoMms.internal_static_io_github_pixelmonaskarion_protomms_proto_Message_descriptor;
      }

      @java.lang.Override
      public io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message getDefaultInstanceForType() {
        return io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message.getDefaultInstance();
      }

      @java.lang.Override
      public io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message build() {
        io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message buildPartial() {
        io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message result = new io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message result) {
        if (recipientsBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0)) {
            recipients_ = java.util.Collections.unmodifiableList(recipients_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.recipients_ = recipients_;
        } else {
          result.recipients_ = recipientsBuilder_.build();
        }
      }

      private void buildPartial0(io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.text_ = text_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.attachments_ = attachments_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.messageId_ = messageId_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.sender_ = senderBuilder_ == null
              ? sender_
              : senderBuilder_.build();
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message) {
          return mergeFrom((io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message other) {
        if (other == io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message.getDefaultInstance()) return this;
        if (other.hasText()) {
          text_ = other.text_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasAttachments()) {
          attachments_ = other.attachments_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getMessageId().isEmpty()) {
          messageId_ = other.messageId_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.hasSender()) {
          mergeSender(other.getSender());
        }
        if (recipientsBuilder_ == null) {
          if (!other.recipients_.isEmpty()) {
            if (recipients_.isEmpty()) {
              recipients_ = other.recipients_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureRecipientsIsMutable();
              recipients_.addAll(other.recipients_);
            }
            onChanged();
          }
        } else {
          if (!other.recipients_.isEmpty()) {
            if (recipientsBuilder_.isEmpty()) {
              recipientsBuilder_.dispose();
              recipientsBuilder_ = null;
              recipients_ = other.recipients_;
              bitField0_ = (bitField0_ & ~0x00000010);
              recipientsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRecipientsFieldBuilder() : null;
            } else {
              recipientsBuilder_.addAllMessages(other.recipients_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                text_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                attachments_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                messageId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                input.readMessage(
                    getSenderFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address m =
                    input.readMessage(
                        io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address.parser(),
                        extensionRegistry);
                if (recipientsBuilder_ == null) {
                  ensureRecipientsIsMutable();
                  recipients_.add(m);
                } else {
                  recipientsBuilder_.addMessage(m);
                }
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object text_ = "";
      /**
       * <code>optional string text = 1;</code>
       * @return Whether the text field is set.
       */
      public boolean hasText() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string text = 1;</code>
       * @return The text.
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string text = 1;</code>
       * @return The bytes for text.
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string text = 1;</code>
       * @param value The text to set.
       * @return This builder for chaining.
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        text_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional string text = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearText() {
        text_ = getDefaultInstance().getText();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>optional string text = 1;</code>
       * @param value The bytes for text to set.
       * @return This builder for chaining.
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        text_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object attachments_ = "";
      /**
       * <code>optional string attachments = 2;</code>
       * @return Whether the attachments field is set.
       */
      public boolean hasAttachments() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string attachments = 2;</code>
       * @return The attachments.
       */
      public java.lang.String getAttachments() {
        java.lang.Object ref = attachments_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          attachments_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string attachments = 2;</code>
       * @return The bytes for attachments.
       */
      public com.google.protobuf.ByteString
          getAttachmentsBytes() {
        java.lang.Object ref = attachments_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          attachments_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string attachments = 2;</code>
       * @param value The attachments to set.
       * @return This builder for chaining.
       */
      public Builder setAttachments(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        attachments_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional string attachments = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAttachments() {
        attachments_ = getDefaultInstance().getAttachments();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>optional string attachments = 2;</code>
       * @param value The bytes for attachments to set.
       * @return This builder for chaining.
       */
      public Builder setAttachmentsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        attachments_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object messageId_ = "";
      /**
       * <code>string message_id = 3;</code>
       * @return The messageId.
       */
      public java.lang.String getMessageId() {
        java.lang.Object ref = messageId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          messageId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message_id = 3;</code>
       * @return The bytes for messageId.
       */
      public com.google.protobuf.ByteString
          getMessageIdBytes() {
        java.lang.Object ref = messageId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message_id = 3;</code>
       * @param value The messageId to set.
       * @return This builder for chaining.
       */
      public Builder setMessageId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        messageId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string message_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageId() {
        messageId_ = getDefaultInstance().getMessageId();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string message_id = 3;</code>
       * @param value The bytes for messageId to set.
       * @return This builder for chaining.
       */
      public Builder setMessageIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        messageId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address sender_;
      private com.google.protobuf.SingleFieldBuilderV3<
          io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address, io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address.Builder, io.github.pixelmonaskarion.protomms.proto.ProtoMms.AddressOrBuilder> senderBuilder_;
      /**
       * <code>.io.github.pixelmonaskarion.protomms.proto.Address sender = 4;</code>
       * @return Whether the sender field is set.
       */
      public boolean hasSender() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>.io.github.pixelmonaskarion.protomms.proto.Address sender = 4;</code>
       * @return The sender.
       */
      public io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address getSender() {
        if (senderBuilder_ == null) {
          return sender_ == null ? io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address.getDefaultInstance() : sender_;
        } else {
          return senderBuilder_.getMessage();
        }
      }
      /**
       * <code>.io.github.pixelmonaskarion.protomms.proto.Address sender = 4;</code>
       */
      public Builder setSender(io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address value) {
        if (senderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sender_ = value;
        } else {
          senderBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.io.github.pixelmonaskarion.protomms.proto.Address sender = 4;</code>
       */
      public Builder setSender(
          io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address.Builder builderForValue) {
        if (senderBuilder_ == null) {
          sender_ = builderForValue.build();
        } else {
          senderBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.io.github.pixelmonaskarion.protomms.proto.Address sender = 4;</code>
       */
      public Builder mergeSender(io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address value) {
        if (senderBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
            sender_ != null &&
            sender_ != io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address.getDefaultInstance()) {
            getSenderBuilder().mergeFrom(value);
          } else {
            sender_ = value;
          }
        } else {
          senderBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.io.github.pixelmonaskarion.protomms.proto.Address sender = 4;</code>
       */
      public Builder clearSender() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sender_ = null;
        if (senderBuilder_ != null) {
          senderBuilder_.dispose();
          senderBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.io.github.pixelmonaskarion.protomms.proto.Address sender = 4;</code>
       */
      public io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address.Builder getSenderBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getSenderFieldBuilder().getBuilder();
      }
      /**
       * <code>.io.github.pixelmonaskarion.protomms.proto.Address sender = 4;</code>
       */
      public io.github.pixelmonaskarion.protomms.proto.ProtoMms.AddressOrBuilder getSenderOrBuilder() {
        if (senderBuilder_ != null) {
          return senderBuilder_.getMessageOrBuilder();
        } else {
          return sender_ == null ?
              io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address.getDefaultInstance() : sender_;
        }
      }
      /**
       * <code>.io.github.pixelmonaskarion.protomms.proto.Address sender = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address, io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address.Builder, io.github.pixelmonaskarion.protomms.proto.ProtoMms.AddressOrBuilder> 
          getSenderFieldBuilder() {
        if (senderBuilder_ == null) {
          senderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address, io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address.Builder, io.github.pixelmonaskarion.protomms.proto.ProtoMms.AddressOrBuilder>(
                  getSender(),
                  getParentForChildren(),
                  isClean());
          sender_ = null;
        }
        return senderBuilder_;
      }

      private java.util.List<io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address> recipients_ =
        java.util.Collections.emptyList();
      private void ensureRecipientsIsMutable() {
        if (!((bitField0_ & 0x00000010) != 0)) {
          recipients_ = new java.util.ArrayList<io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address>(recipients_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address, io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address.Builder, io.github.pixelmonaskarion.protomms.proto.ProtoMms.AddressOrBuilder> recipientsBuilder_;

      /**
       * <code>repeated .io.github.pixelmonaskarion.protomms.proto.Address recipients = 5;</code>
       */
      public java.util.List<io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address> getRecipientsList() {
        if (recipientsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(recipients_);
        } else {
          return recipientsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .io.github.pixelmonaskarion.protomms.proto.Address recipients = 5;</code>
       */
      public int getRecipientsCount() {
        if (recipientsBuilder_ == null) {
          return recipients_.size();
        } else {
          return recipientsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .io.github.pixelmonaskarion.protomms.proto.Address recipients = 5;</code>
       */
      public io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address getRecipients(int index) {
        if (recipientsBuilder_ == null) {
          return recipients_.get(index);
        } else {
          return recipientsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .io.github.pixelmonaskarion.protomms.proto.Address recipients = 5;</code>
       */
      public Builder setRecipients(
          int index, io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address value) {
        if (recipientsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecipientsIsMutable();
          recipients_.set(index, value);
          onChanged();
        } else {
          recipientsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .io.github.pixelmonaskarion.protomms.proto.Address recipients = 5;</code>
       */
      public Builder setRecipients(
          int index, io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address.Builder builderForValue) {
        if (recipientsBuilder_ == null) {
          ensureRecipientsIsMutable();
          recipients_.set(index, builderForValue.build());
          onChanged();
        } else {
          recipientsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .io.github.pixelmonaskarion.protomms.proto.Address recipients = 5;</code>
       */
      public Builder addRecipients(io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address value) {
        if (recipientsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecipientsIsMutable();
          recipients_.add(value);
          onChanged();
        } else {
          recipientsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .io.github.pixelmonaskarion.protomms.proto.Address recipients = 5;</code>
       */
      public Builder addRecipients(
          int index, io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address value) {
        if (recipientsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecipientsIsMutable();
          recipients_.add(index, value);
          onChanged();
        } else {
          recipientsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .io.github.pixelmonaskarion.protomms.proto.Address recipients = 5;</code>
       */
      public Builder addRecipients(
          io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address.Builder builderForValue) {
        if (recipientsBuilder_ == null) {
          ensureRecipientsIsMutable();
          recipients_.add(builderForValue.build());
          onChanged();
        } else {
          recipientsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .io.github.pixelmonaskarion.protomms.proto.Address recipients = 5;</code>
       */
      public Builder addRecipients(
          int index, io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address.Builder builderForValue) {
        if (recipientsBuilder_ == null) {
          ensureRecipientsIsMutable();
          recipients_.add(index, builderForValue.build());
          onChanged();
        } else {
          recipientsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .io.github.pixelmonaskarion.protomms.proto.Address recipients = 5;</code>
       */
      public Builder addAllRecipients(
          java.lang.Iterable<? extends io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address> values) {
        if (recipientsBuilder_ == null) {
          ensureRecipientsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, recipients_);
          onChanged();
        } else {
          recipientsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .io.github.pixelmonaskarion.protomms.proto.Address recipients = 5;</code>
       */
      public Builder clearRecipients() {
        if (recipientsBuilder_ == null) {
          recipients_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          recipientsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .io.github.pixelmonaskarion.protomms.proto.Address recipients = 5;</code>
       */
      public Builder removeRecipients(int index) {
        if (recipientsBuilder_ == null) {
          ensureRecipientsIsMutable();
          recipients_.remove(index);
          onChanged();
        } else {
          recipientsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .io.github.pixelmonaskarion.protomms.proto.Address recipients = 5;</code>
       */
      public io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address.Builder getRecipientsBuilder(
          int index) {
        return getRecipientsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .io.github.pixelmonaskarion.protomms.proto.Address recipients = 5;</code>
       */
      public io.github.pixelmonaskarion.protomms.proto.ProtoMms.AddressOrBuilder getRecipientsOrBuilder(
          int index) {
        if (recipientsBuilder_ == null) {
          return recipients_.get(index);  } else {
          return recipientsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .io.github.pixelmonaskarion.protomms.proto.Address recipients = 5;</code>
       */
      public java.util.List<? extends io.github.pixelmonaskarion.protomms.proto.ProtoMms.AddressOrBuilder> 
           getRecipientsOrBuilderList() {
        if (recipientsBuilder_ != null) {
          return recipientsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(recipients_);
        }
      }
      /**
       * <code>repeated .io.github.pixelmonaskarion.protomms.proto.Address recipients = 5;</code>
       */
      public io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address.Builder addRecipientsBuilder() {
        return getRecipientsFieldBuilder().addBuilder(
            io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address.getDefaultInstance());
      }
      /**
       * <code>repeated .io.github.pixelmonaskarion.protomms.proto.Address recipients = 5;</code>
       */
      public io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address.Builder addRecipientsBuilder(
          int index) {
        return getRecipientsFieldBuilder().addBuilder(
            index, io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address.getDefaultInstance());
      }
      /**
       * <code>repeated .io.github.pixelmonaskarion.protomms.proto.Address recipients = 5;</code>
       */
      public java.util.List<io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address.Builder> 
           getRecipientsBuilderList() {
        return getRecipientsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address, io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address.Builder, io.github.pixelmonaskarion.protomms.proto.ProtoMms.AddressOrBuilder> 
          getRecipientsFieldBuilder() {
        if (recipientsBuilder_ == null) {
          recipientsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address, io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address.Builder, io.github.pixelmonaskarion.protomms.proto.ProtoMms.AddressOrBuilder>(
                  recipients_,
                  ((bitField0_ & 0x00000010) != 0),
                  getParentForChildren(),
                  isClean());
          recipients_ = null;
        }
        return recipientsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.github.pixelmonaskarion.protomms.proto.Message)
    }

    // @@protoc_insertion_point(class_scope:io.github.pixelmonaskarion.protomms.proto.Message)
    private static final io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message();
    }

    public static io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.github.pixelmonaskarion.protomms.proto.ProtoMms.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AddressOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.github.pixelmonaskarion.protomms.proto.Address)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string address = 1;</code>
     * @return The address.
     */
    java.lang.String getAddress();
    /**
     * <code>string address = 1;</code>
     * @return The bytes for address.
     */
    com.google.protobuf.ByteString
        getAddressBytes();
  }
  /**
   * Protobuf type {@code io.github.pixelmonaskarion.protomms.proto.Address}
   */
  public static final class Address extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.github.pixelmonaskarion.protomms.proto.Address)
      AddressOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Address.newBuilder() to construct.
    private Address(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Address() {
      address_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Address();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.pixelmonaskarion.protomms.proto.ProtoMms.internal_static_io_github_pixelmonaskarion_protomms_proto_Address_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.pixelmonaskarion.protomms.proto.ProtoMms.internal_static_io_github_pixelmonaskarion_protomms_proto_Address_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address.class, io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address.Builder.class);
    }

    public static final int ADDRESS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object address_ = "";
    /**
     * <code>string address = 1;</code>
     * @return The address.
     */
    @java.lang.Override
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <code>string address = 1;</code>
     * @return The bytes for address.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(address_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, address_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(address_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, address_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address)) {
        return super.equals(obj);
      }
      io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address other = (io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address) obj;

      if (!getAddress()
          .equals(other.getAddress())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.github.pixelmonaskarion.protomms.proto.Address}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.github.pixelmonaskarion.protomms.proto.Address)
        io.github.pixelmonaskarion.protomms.proto.ProtoMms.AddressOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.pixelmonaskarion.protomms.proto.ProtoMms.internal_static_io_github_pixelmonaskarion_protomms_proto_Address_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.pixelmonaskarion.protomms.proto.ProtoMms.internal_static_io_github_pixelmonaskarion_protomms_proto_Address_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address.class, io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address.Builder.class);
      }

      // Construct using io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        address_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.pixelmonaskarion.protomms.proto.ProtoMms.internal_static_io_github_pixelmonaskarion_protomms_proto_Address_descriptor;
      }

      @java.lang.Override
      public io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address getDefaultInstanceForType() {
        return io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address.getDefaultInstance();
      }

      @java.lang.Override
      public io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address build() {
        io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address buildPartial() {
        io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address result = new io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.address_ = address_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address) {
          return mergeFrom((io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address other) {
        if (other == io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address.getDefaultInstance()) return this;
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                address_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object address_ = "";
      /**
       * <code>string address = 1;</code>
       * @return The address.
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string address = 1;</code>
       * @return The bytes for address.
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string address = 1;</code>
       * @param value The address to set.
       * @return This builder for chaining.
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        address_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string address = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddress() {
        address_ = getDefaultInstance().getAddress();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string address = 1;</code>
       * @param value The bytes for address to set.
       * @return This builder for chaining.
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        address_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.github.pixelmonaskarion.protomms.proto.Address)
    }

    // @@protoc_insertion_point(class_scope:io.github.pixelmonaskarion.protomms.proto.Address)
    private static final io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address();
    }

    public static io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Address>
        PARSER = new com.google.protobuf.AbstractParser<Address>() {
      @java.lang.Override
      public Address parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Address> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Address> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.github.pixelmonaskarion.protomms.proto.ProtoMms.Address getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_github_pixelmonaskarion_protomms_proto_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_github_pixelmonaskarion_protomms_proto_Message_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_github_pixelmonaskarion_protomms_proto_Address_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_github_pixelmonaskarion_protomms_proto_Address_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n9io/github/pixelmonaskarion/protomms/pr" +
      "oto/proto_mms.proto\022)io.github.pixelmona" +
      "skarion.protomms.proto\"\357\001\n\007Message\022\021\n\004te" +
      "xt\030\001 \001(\tH\000\210\001\001\022\030\n\013attachments\030\002 \001(\tH\001\210\001\001\022" +
      "\022\n\nmessage_id\030\003 \001(\t\022B\n\006sender\030\004 \001(\01322.io" +
      ".github.pixelmonaskarion.protomms.proto." +
      "Address\022F\n\nrecipients\030\005 \003(\01322.io.github." +
      "pixelmonaskarion.protomms.proto.AddressB" +
      "\007\n\005_textB\016\n\014_attachments\"\032\n\007Address\022\017\n\007a" +
      "ddress\030\001 \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_github_pixelmonaskarion_protomms_proto_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_github_pixelmonaskarion_protomms_proto_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_github_pixelmonaskarion_protomms_proto_Message_descriptor,
        new java.lang.String[] { "Text", "Attachments", "MessageId", "Sender", "Recipients", "Text", "Attachments", });
    internal_static_io_github_pixelmonaskarion_protomms_proto_Address_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_github_pixelmonaskarion_protomms_proto_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_github_pixelmonaskarion_protomms_proto_Address_descriptor,
        new java.lang.String[] { "Address", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
